#生产环境
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQuer ies=true
    username: root
    password: 123456

  thymeleaf:
    cache: false #开启缓存
  redis:
    host: 192.168.71.128
    port: 6379
    password:
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大控线连接
        min-idle: 0 #连接池中的最小空闲连接
imgFilePath: D:/MyCode/src/main/resources/static/static/img/
lucenePath: D:/MyCode/lucene/